#!/bin/bash
if [ "$1" == "tor" ]; then
	sudo -u debian-tor tor
	exit
fi

ServiceUser="MorningNoLogin"
if id "$ServiceUser" > /dev/null 2>&1; then
	test -e ./bin/MorningMessenger
	if [ "$?" == "0" ]; then
		if [ "$1" == "tor" ]; then
			sudo -u $ServiceUser torsocks ./bin/MorningMessenger
		else
			sudo -u $ServiceUser ./bin/MorningMessenger
		fi
	else
		echo "[ERROR] Binary not found. Run 'make'"
	fi
else
	echo "[ERROR] Service user not found. Run 'make install'"
fi

